# -*- coding: utf-8 -*-
"""BIOMEDICAL IMAGE ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/muhammadumer1534/biomedical-image-analysis.036f6fc7-93e1-4a2b-b6e4-14465c079336.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260519/auto/storage/goog4_request%26X-Goog-Date%3D20260519T162956Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D12c1591678e9ec242bb210e55b4342d3826b659bca6642d026a2968c0393f85589cad040fd559b681727c07bc4f9f6c0c676e489d67548f7975faa9c7a8089d8c82073aa1bb0243a40f7b7bb1f0da81911804cf82bc925219f457550fe18e843b8258d6f2c382a5506d3c3e918e9f98a655eeae0f0dd7ffd38d803499267c6bb19398ea9b63d6f6b1bc7e0672aa7e8940baf4576bebfc1924afd22bb726101b6369276353504c60346976b9df5246280f74987fa4a2a204527f162833532f27983ce62bdbfefe18ab3bb71cc70b35e25aa17d55e295f389efa0eca90831651cb8ef88044d5b864245bea84238311b9cc64a1ef932f1dfabb2e47678d2518a09b
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
paultimothymooney_chest_xray_pneumonia_path = kagglehub.dataset_download('paultimothymooney/chest-xray-pneumonia')

print('Data source import complete.')

!pip install tensorflow matplotlib seaborn scikit-learn





import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import os

print(os.listdir('/kaggle/input/datasets/paultimothymooney'))

print(os.listdir('/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia'))

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(
    rescale=1./255
)

train_data = train_datagen.flow_from_directory(
    '/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/train',
    target_size=(224, 224),
    batch_size=16,
    class_mode='binary'
)

val_data = test_datagen.flow_from_directory(
    '/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/val',
    target_size=(224, 224),
    batch_size=16,
    class_mode='binary'
)

test_data = test_datagen.flow_from_directory(
    '/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/test',
    target_size=(224, 224),
    batch_size=16,
    class_mode='binary',
    shuffle=False
)

images, labels = next(train_data)

plt.figure(figsize=(10,10))

for i in range(9):

    plt.subplot(3,3,i+1)

    plt.imshow(images[i])

    if labels[i] == 1:
        plt.title("PNEUMONIA")
    else:
        plt.title("NORMAL")

    plt.axis("off")

plt.show()

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

model = Sequential([

    base_model,

    GlobalAveragePooling2D(),

    Dropout(0.3),

    Dense(128, activation='relu'),

    Dense(1, activation='sigmoid')

])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

loss, accuracy = model.evaluate(test_data)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('Model Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend(['Train', 'Validation'])

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('Model Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend(['Train', 'Validation'])

plt.show()

predictions = model.predict(test_data)

predicted_classes = []

for i in predictions:

    if i > 0.5:
        predicted_classes.append(1)
    else:
        predicted_classes.append(0)

true_classes = test_data.classes

print(classification_report(true_classes, predicted_classes))

cm = confusion_matrix(true_classes, predicted_classes)

plt.figure(figsize=(6,6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

model.save("pneumonia_detection_model.h5")

print("Model Saved Successfully")

from tensorflow.keras.models import load_model

loaded_model = load_model("pneumonia_detection_model.h5")

print("Model Loaded Successfully")

from tensorflow.keras.preprocessing import image

img_path = '/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/test/NORMAL/IM-0001-0001.jpeg'

img = image.load_img(img_path, target_size=(224,224))

img_array = image.img_to_array(img)

img_array = np.expand_dims(img_array, axis=0)

img_array = img_array / 255.0

prediction = loaded_model.predict(img_array)

if prediction[0][0] > 0.5:
    print("PNEUMONIA DETECTED")
else:
    print("NORMAL")

import random
import matplotlib.pyplot as plt

def show_images(generator, title):
    images, labels = next(generator)

    plt.figure(figsize=(12, 12))
    plt.suptitle(title)

    for i in range(16):
        plt.subplot(4, 4, i+1)
        plt.imshow(images[i])

        if labels[i] == 1:
            plt.title("PNEUMONIA")
        else:
            plt.title("NORMAL")

        plt.axis("off")

    plt.show()

show_images(train_data, "Training Dataset Samples")

import numpy as np

print("Train classes:", train_data.class_indices)

print("Test classes:", test_data.class_indices)

import os

train_normal = len(os.listdir('/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/train/NORMAL'))
train_pneumonia = len(os.listdir('/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/train/PNEUMONIA'))

print("Normal images:", train_normal)
print("Pneumonia images:", train_pneumonia)

prediction = loaded_model.predict(img_array)

print("Model confidence:", prediction[0][0])

if prediction[0][0] > 0.5:
    print("PNEUMONIA")
else:
    print("NORMAL")

import numpy as np

wrong = 0

for i in range(len(predictions)):
    if predicted_classes[i] != true_classes[i]:
        wrong += 1

print("Wrong predictions:", wrong)
print("Total samples:", len(true_classes))